### ISSUE TITLE
[SUGGESTION]Replay Buffer and "Twitch Chat"

### ISSUE THREAD

**Issue by xx1182** [Kounex/obs_blade#14]
Well, I could do it, but it's going to take me some time to get accustomed to the source code, you could do it in like 5 minutes, it's just two buttons "start replay buffer" and "save replay"

Second, Twitch chat, while you can read the chat, there is no way to replay, to write, I don't know if this is a limitation or something, it's no big deal, but the replay is a really useful function.

Regards.

**Comment by Kounex** [comment]
I added the replay buffer capability to my backlog - is the replay buffer functionality supported for streaming + recording or just one of them?

The chats are currently just WebViews so there is nothing I'm really in control of. I'm able to write on multiple devices - once I try to post something, I will be forwarded to log in. I also have not heard of this problem before. Maybe you have some WebView restrictions on OS level? Android for example can adjust JavaScript usage in Browsers etc.

**Comment by xx1182** [comment]
> I added the replay buffer capability to my backlog - is the replay buffer functionality supported for streaming + recording or just one of them?
> 
> The chats are currently just WebViews so there is nothing I'm really in control of. I'm able to write on multiple devices - once I try to post something, I will be forwarded to log in. I also have not heard of this problem before. Maybe you have some WebView restrictions on OS level? Android for example can adjust JavaScript usage in Browsers etc.

Yes, the replay buffer is both available while streaming and while recording, and even both at the same time.
For the chat, my default browser is Chrome Dev, so I guess it switched the webview to that, I could try with the default browser which is Samsung Internet. My Android version is 12. 
Regards.

**Comment by Kounex** [comment]
Alright thanks for the info! I will update this issue once this feature is in my dev environment / getting into the stores when I'm able to work on the app again.

**Comment by xx1182** [comment]
> Alright thanks for the info! I will update this issue once this feature is in my dev environment / getting into the stores when I'm able to work on the app again.

Updates, I did some tests:
I tried changing default browser to no avail, pressing [Send a message] simply does not pop-up the keyboard, pressing [Chat] does pop-up the Login Form, but the Keyboard does not pop-up, I tried to also switch keyboards, from Gboard to Samsung Keyboard to no avail; but **connecting an external keyboard it let's you write and log-in as intended.**

I have one of those new fancy devices that folds etc, and it works as intended, in folded mode is Phone interface, when unfolded is tablet interface(no need to reload or restart the app, don't even have to set "force tablet mode", does it automatically).

This should be Android12 with OneUI, I think it's something simple as a flag for the webview to enable "interactivity" that came with Android12, I'm not sure but, alot of users and developers(I don't use Java, only in highschool to make Robot hands move) lament that Android12 brought a lot of restrictions, it even kills processes automatically if they use extensive CPU(which is not your case as wakelock works as intended).

Regards.

**Comment by Kounex** [comment]
v3.0.0 is rolling out which adds replay buffer support and should improve chat integration - enjoy! 🎉

**Comment by xx1182** [comment]
> v3.0.0 is rolling out which adds replay buffer support and should improve chat integration - enjoy! 🎉

Thanks, I'll download from here, and for the Play Release, maybe you forgot? Cheers!

**Comment by Kounex** [comment]
Submitted app to Apple App Store and Google Play simultaneously - Apple released 3.0.0 and 3.0.1 already, Google Play is still in review... 🥲
