### ISSUE TITLE
Suggestion - add stream information and activity feed 

### ISSUE THREAD

**Issue by thegamingstig** [Kounex/obs_blade#15]
This app has been perfect when I tried streaming IRL at an exhibition event. As I was using it, there are some things I wish to see being included in this app:

1.  Have the ability to update my stream information (ability to change the stream title, stream category, or update tags)
2. An activity feed panel that shows past events of new follows, subs, cheers, raids, and host.

You did a great job with this app. GOOD JOB!

**Comment by Kounex** [comment]
Glad you enjoy using the app! :)

Currently I'm not interacting with streaming platforms directly and the information you mentioned is not handled by OBS itself, therefore it's not part of the WebSocket plugin I'm relying on.

I thought about adding the ability to add own WebViews, meaning you could add a card where you can visit any website you need like a browser showing stuff like latest activities you mentioned. The problem though: both app stores are aware of the ability of apps to include browser like behaviour and are very strict about that. Someone could potentially visit pages containing harmful content. I don't want to risk something like this.

Last option I could think of is enabling a fix set of websites and enable to modify the URL after the base. For example:

https://twitch.com/**<you can modify this part as needed>**

Is it possible to access all the necessary information from twitch itself or are you relying on other websites as well?

**Comment by thegamingstig** [comment]
I was hoping your app can pull that information directly from OBS Studio, since it generate docks for the mention when I connect with my stream login instead of using the streamkey. But I guess I will have to learn all the chat command or have my mods to change the stream information as I stream.

**Comment by richtopia** [comment]
Sorry to grave-dig a closed comment. I just want to say the ability to add WebViews - allowing modifying the Twitch (or other platform) would be great. 

The app is excellent and I really appreciate the work done. My dream is to leave my computer running during a multi-day trip and use OBS Blade to start/stop streams which it does well, but unfortunately today I have to remote to the desktop for Title configuration.

**Comment by thegamingstig** [comment]
https://dashboard.twitch.tv/popout/u/"**twitchuserid**"/stream-manager/edit-stream-info

I found this for twitch.
