### ISSUE TITLE
Feature request: permanent screen power on

### ISSUE THREAD

**Issue by comerc** [Kounex/obs_blade#2]
Very cool app, thanks! Please add this necessary feature. :)

**Comment by Kounex** [comment]
I will implement that, sounds good! :)

**Comment by comerc** [comment]
I need this feature very well! I have > 500 live-coding about Flutter on [Youtube-channel](https://www.youtube.com/channel/UCEVmXqOovS2OExZxe9Mh53Q) :)

**Comment by Kounex** [comment]
Implemented in version 1.1.0, submitted to both app stores, waiting for approval. Closing this as soon as the app goes live in both stores! :)

**Comment by Kounex** [comment]
Accepted by both App Stores with the release of version 1.1.1

**Comment by comerc** [comment]
![photo_2020-11-05_10-18-44](https://user-images.githubusercontent.com/1025241/98209757-8c805f00-1f50-11eb-84ae-9e775a15389a.jpg)

Thanks!
