### ISSUE TITLE
Pause bug with new version (no resume button)

### ISSUE THREAD

**Issue by kibbblz** [Kounex/obs_blade#20]
Just tested the new version. When I pause using the app, it pauses fine, but it won't show a resume button and if I press pause again anyway, it doesn't resume recording althrough the timer starts to run again on the app but not on the desktop... it will stay paused no matter what unless I manually unpause on desktop. Thanks!

**Comment by Kounex** [comment]
Oh that went under my radar, great find! I will test that again and fix it! :)

**Comment by Kounex** [comment]
3.0.1 is pushed and should be online tomorrow - sorry!
