### ISSUE TITLE
Latest version bug

### ISSUE THREAD

**Issue by sanunes27** [Kounex/obs_blade#22]
Hi, thank you for this great app. I use the ios version. With the new version, I noticed the scenes order is the opposite of what we have in obs. So, my first scene in OBS is always the last on the list on the app. It’s really confusing to manage the scenes this way. Is there a way to fix it?

Again, thank you for this great plugin.
Sam

**Comment by sanunes27** [comment]
> You are right, the order changed without me changing the logic - seems the way I receive it from the API itself changed.
> 
> I will sort it myself and push an update later :)

Thank you! I thought I changed something wrong and was going crazy on the settings. Thank you! Your work has helped me so much this year!

**Comment by Kounex** [comment]
Glad to hear that! :)

I pushed version 3.0.2 to the stores which fixes this, should be downloadable soon!
