### ISSUE TITLE
Lastest Vesion Crashes as soon as it connects

### ISSUE THREAD

**Issue by xx1182** [Kounex/obs_blade#23]
Like the title states, i have OBS 27.2.4 and as soon as i touch connect, it crashes, i would give you a log, but there is none.
I've also tried with scanQR code.
Regards.

```
: [obs-websocket] [WebSocketServer::onOpen] New WebSocket client has connected from [::ffff:192.168.1.7]:44922
: [obs-websocket] [WebSocketServer::onClose] WebSocket client `[::ffff:192.168.1.7]:44922` has disconnected with code `1006` and reason: Connessione interrotta dal corrispondente(It's italian it means "Connection interrupted by the corrispondent", which i guess it means client lol)
```

**Comment by xx1182** [comment]
Ok, fixed, i had to go to:
Settings->Data Management->All Data and press "Clear" i think you should add atleast a disclamer saying: If you updating, do this.

Also, before i did this, i've tried to Delete the Cache, and Reinstall the app, the only thing that worked was deleting "All data" from within the app.

Regards.

I'm not closing it, because pheraps someone has the same problems.

**Comment by xx1182** [comment]
Wow, it crashes again, you have to delete data everytime, atleast for me.

**Comment by Kounex** [comment]
This very odd - on what device are you on (which operating system version)? What if you don't save anything (no chat, no saved connection etc.): does it still crash on connect?

**Comment by Ghostkwebb** [comment]
I have the same problem. 

> This very odd - on what device are you on (which operating system version)? What if you don't save anything (no chat, no saved connection etc.): does it still crash on connect?

I have the same problem. I'm on Android 10 Redmi 8a dual and it still crashes even when you don't save anything.

**Comment by Kounex** [comment]
What are you able to do before it crashes? Can you see a pattern when you can initiate the app crash?

**Comment by Ghostkwebb** [comment]
Just starting the app like normal, then tried to connect and crashed. So i tried to clear all data from app as mentioned above and then tried to connect and it worked, so I scrolled a little as nothing was saved to add a Twitch username and when I clicked save for the username it crashed again.

**Comment by Ghostkwebb** [comment]
Video for reference  

https://user-images.githubusercontent.com/61558762/187695938-e650d6c5-43be-49f4-8de3-6ed3a91feabd.mp4

**Comment by Ghostkwebb** [comment]
> What are you able to do before it crashes? Can you see a pattern when you can initiate the app crash?

So that's the summary

**Comment by Kounex** [comment]
Okay wow, wtf.

Thanks a lot for the video. It has to be a storage / persistence problem with the package I'm using - even though it is the same package as always and I haven't really changed anything around that. Has to be a faulty update...

I will try to find an Android device from friends / family where I can replicate this issue since the android phone I'm using does not have this problem!

**Comment by Ghostkwebb** [comment]
Did my messages get deleted?

> What are you able to do before it crashes? Can you see a pattern when you can initiate the app crash?

**Comment by Ghostkwebb** [comment]
I hope this problem gets fixed as I really like this app and have been using it for quite a while now

**Comment by Kounex** [comment]
I found the problem:

- The framework I'm using is Flutter
- For displaying the stream chats, I'm using a WebView (basically an embedded browser which is able to display web pages
- In Flutter, WebViews are implemented as PlatformViews, basically means it uses the WebView of the operating system (Android / iOS) and does not have an own implementation (which is good)
- BUT: the current stable version of Flutter (v3.0.5) is creating PlatformViews differently than previously done. This should not be a problem in general, but our WebView implementation is actually not working on some Android versions, super random

Luckily: Flutter reached a milestone yesterday and released Flutter v3.3.0 which adjusted a lot, one being the way PlatformViews are created again. This seems to solve the problem. It at least worked on the phone of a friend of mine.

I will push another version - I will leave another comment when it's online. Would appreciate any feedback!

**Comment by Ghostkwebb** [comment]
> I found the problem:
> 
> * The framework I'm using is Flutter
> * For displaying the stream chats, I'm using a WebView (basically an embedded browser which is able to display web pages
> * In Flutter, WebViews are implemented as PlatformViews, basically means it uses the WebView of the operating system (Android / iOS) and does not have an own implementation (which is good)
> * BUT: the current stable version of Flutter (v3.0.5) is creating PlatformViews differently than previously done. This should not be a problem in general, but our WebView implementation is actually not working on some Android versions, super random
> 
> Luckily: Flutter reached a milestone yesterday and released Flutter v3.3.0 which adjusted a lot, one being the way PlatformViews are created again. This seems to solve the problem. It at least worked on the phone of a friend of mine.
> 
> I will push another version - I will leave another comment when it's online. Would appreciate any feedback!

Till when will you push another update cause I have a stream soon :( and I'm reliant on this app

**Comment by Kounex** [comment]
<img width="236" alt="image" src="https://user-images.githubusercontent.com/13067046/187719910-de396c15-5712-4d19-af4f-97ca236eed2a.png">

I pushed it - now it's up to Google Play to review and release it to the store.

As a workaround, you can use the app without the chat feature. Open the chat in your browser instead and use OBS Blade for the rest since this crash only happens when you add a chat!

**Comment by xx1182** [comment]
> I found the problem:
> 
> * The framework I'm using is Flutter
> * For displaying the stream chats, I'm using a WebView (basically an embedded browser which is able to display web pages
> * In Flutter, WebViews are implemented as PlatformViews, basically means it uses the WebView of the operating system (Android / iOS) and does not have an own implementation (which is good)
> * BUT: the current stable version of Flutter (v3.0.5) is creating PlatformViews differently than previously done. This should not be a problem in general, but our WebView implementation is actually not working on some Android versions, super random
> 
> Luckily: Flutter reached a milestone yesterday and released Flutter v3.3.0 which adjusted a lot, one being the way PlatformViews are created again. This seems to solve the problem. It at least worked on the phone of a friend of mine.
> 
> I will push another version - I will leave another comment when it's online. Would appreciate any feedback!


> <img alt="image" width="236" src="https://user-images.githubusercontent.com/13067046/187719910-de396c15-5712-4d19-af4f-97ca236eed2a.png">
> 
> I pushed it - now it's up to Google Play to review and release it to the store.
> 
> As a workaround, you can use the app without the chat feature. Open the chat in your browser instead and use OBS Blade for the rest since this crash only happens when you have any chat active!

Maybe release an APK... In releases for the furry lolicon Futanari free software enthusiast(not me) or on f-droid
Thanks.

**Comment by Ghostkwebb** [comment]
> <img alt="image" width="236" src="https://user-images.githubusercontent.com/13067046/187719910-de396c15-5712-4d19-af4f-97ca236eed2a.png">
> 
> I pushed it - now it's up to Google Play to review and release it to the store.
> 
> As a workaround, you can use the app without the chat feature. Open the chat in your browser instead and use OBS Blade for the rest since this crash only happens when you have any chat active!

You do realise that chat is one of the good features and that while playing a game i can't see chat so a stream deck with built in chat features is the dream.

**Comment by Kounex** [comment]
Yes of course - it's just meant as a workaround as long as the update is not out yet! ;)

**Comment by xx1182** [comment]
> > <img alt="image" width="236" src="https://user-images.githubusercontent.com/13067046/187719910-de396c15-5712-4d19-af4f-97ca236eed2a.png">
> > I pushed it - now it's up to Google Play to review and release it to the store.
> > As a workaround, you can use the app without the chat feature. Open the chat in your browser instead and use OBS Blade for the rest since this crash only happens when you have any chat active!
> 
> You do realise that chat is one of the good features and that while playing a game i can't see chat so a stream deck with built in chat features is the dream.

Yeah, stupid developer can't even do free work correctly what a retard, on another note, any of you know some plugin to make green screen? Like I don't want to buy a green rug and use chroma key...

Regards.

**Comment by Kounex** [comment]
Take a look at that for the green screen topic.

https://www.theverge.com/2022/8/31/23330379/nvidia-broadcast-virtual-green-screen-obs-studio-support

**Comment by xx1182** [comment]
An update has been pushed to the play store, and on that note(I'll update and close if everything fine), since you seem to be more experienced in projects, I've been always using normal stuff,Ike C, C++, golang for fast and easy prototyping, and technically it's very fast and easy to do.

I would like to make a "broadcaster" that mostly run headless, for iptvs, obs witouth graphic card no encoding, give video and it stream, then implement ads etc, on YouTube... The hardware is an old phone;

Simply by using JavaScript and C++ or golang, I don't want to learn ffmpeg include bindings it's a big big... So what would suggestion? I'm almost sure I don't want to implement the rtmp protocol by my own, would that be the best action?

**Comment by Ghostkwebb** [comment]
Thanks for the great support @Kounex !!

**Comment by xx1182** [comment]
Ok, everything works as intended, issue #24 is not affecting since got a big foldable screen, the only possibly "missing feature", which is more of a quality of life, is registering the "return" button as sending a message, on PC one probably makes
new lines to
explain a concept but
Not so often on mobile

Cheers and regards!
