### ISSUE TITLE
Feature Request: Edit sources Example change the text in a text source

### ISSUE THREAD

**Issue by DaBenjamins** [Kounex/obs_blade#30]
Feature Request:
I would like to be able to update/change text and browser sources through OBS Blade

**Comment by thegamingstig** [comment]
That would be nice. I would like to change the file directory/url of the browser source or image source

**Comment by Kounex** [comment]
The idea behind this app is more about controlling OBS - toggling actions like recording / streaming, changing the scenes and having an overview of OBS itself etc. Features like this are less about controlling OBS and more like being a remote OBS client itself. Starting to go on this direction would be tricky - where to stop? Other people would like to add / remove scene items, change properties of sources, change the position of items on the scene and more.

This would in general move this app in another direction and it would add a lot more complexity. I think the OBS client itself should be used for actually building scenes, changing items etc. and this app should remain a controller. Therefore it's not currently planned to extend the app like this!

**Comment by DaBenjamins** [comment]
> The idea behind this app is more about controlling OBS - toggling actions like recording / streaming, changing the scenes and having an overview of OBS itself etc. Features like this are less about controlling OBS and more like being a remote OBS client itself. Starting to go in this direction would be tricky - where to stop? Other people would like to add / remove scene items, change properties of sources, change the position of items on the scene and more.
> 
> This would in general move this app in another direction and it would add a lot more complexity. I think the OBS client itself should be used for actually building scenes, changing items etc. and this app should remain a controller. Therefore it's not currently planned to extend the app like this!

This makes sense, its just in my use case I manage esports broadcasts and I would need to update a teams score text source a few times during the broadcast. that would me nice to do from the remote control app.
