### ISSUE TITLE
How can I build this

### ISSUE THREAD

**Issue by Lucy2003** [Kounex/obs_blade#34]
I can't access the google play, so I think I can try to use the Android SDK to build it.

What I need to do? Please give me some guide and thank you.

**Comment by Kounex** [comment]
I will add a section to the readme on how to build this - but it is basically following this to get the flutter framework set up correctly: https://docs.flutter.dev/get-started/install after that it's just running this as you would with any other Flutter app as described in the docs

**Comment by Lucy2003** [comment]
OK,I'm gonna try it.
