### ISSUE TITLE
[Feature Request] Add Split File Button

### ISSUE THREAD

**Issue by aonphleacs** [Kounex/obs_blade#36]
OBS now supports file splitting! If OBS Blade could have a button that tells OBS to split the file, that would be amazing.
I don't know if the web socket connection supports this or not but if it doesn't support it directly then perhaps sending a hotkey command would work instead.
I could use UP Deck for this but your app is so much easier in terms of setup and so much nicer looking to boot ;)

**Comment by Kounex** [comment]
Hahaha aww thanks 😄 sounds like an awesome feature, I will check if the WebSocket API supports this natively!

I'm planning on implementing hotkeys triggers in the app as well so yes it will eventually be possible nonetheless! But the WebSocket way would be faster - keeping this issue updated! 😊

**Comment by Kounex** [comment]
Ah good catch! I will see how far I can get regarding the hotkey feature in the meantime 😊 Although it will take some time due to the usual time constraints!

**Comment by Kounex** [comment]
Version 3.1.0 now has a hotkey feature in the technical preview state - you should be able to make use of the split file feature now (although not as convenient though) 😊
