### ISSUE TITLE
Cookie settings screen issue

### ISSUE THREAD

**Issue by Cederick** [Kounex/obs_blade#39]
So hey, I have the issue that I can't accept or skip the cookie banner for the twitch chat. I tried everything and it covers up the chat for me all the time so it makes it impossible to use that part of the app.

**Comment by Kounex** [comment]
I assume you are on the latest version of the app? I added extra height to the chat box to hopefully avoid this problem...

Is it still a height issue? Meaning you can't see the accept button? Or is it something else? Could you maybe share a screenshot of your screen while seeing the unskipable banner?

**Comment by Cederick** [comment]
![Screenshot_20221213_232351_com kounex obsBlade](https://user-images.githubusercontent.com/16303253/207457773-fcb06efd-1859-4792-9e51-b0808b62f1dd.jpg)

Clicking accept does nothing at all

**Comment by Kounex** [comment]
Ohhh I know what's causing this!

I will take another look at this issue since it's not that easy to work. I will update this issue once I have news to share! :)

**Comment by Kounex** [comment]
The consent banner problem should be _not existent_ anymore in OBS Blade 3.2.0 👀

I just submitted the update, should be available soon 😊
