### ISSUE TITLE
OBS 29 - Some previous features were removed

### ISSUE THREAD

**Issue by thegamingstig** [Kounex/obs_blade#42]
It appears that the ability to change profile that you added on 3.0.4, and the ability to change scene collection, were removed when update to OBS 29. Please confirm.

**Comment by Kounex** [comment]
You can activate that in the settings tab, they are called "Profiles" and "Scene Collections" in the Dashboard card.

**Comment by thegamingstig** [comment]
ah....THANK YOU!
