### ISSUE TITLE
[Feature Request] Follow OBS' audio mixer source hidden status

### ISSUE THREAD

**Issue by XC3N** [Kounex/obs_blade#43]
First, thanks a lot for the app, it's amazing!

I have a lot of webcams plugged in that I don't want to use audio for, so I hide the audio source in the audio mixer so I can see everything I use at once.

Blade has no way to hide these, so I end up with a lot of muted webcam sources that push out of view the mixer sliders I actually want to use.

Thanks!

**Comment by Kounex** [comment]
Thanks for the kind words! :) 

That feature is in OBS Blade! It's just too well hidden - good that you bring that up. Need to think about a better way to integrate that.

While connected to OBS and you are in the Dashboard, click on the three dots in the app bar and select "Edit Scene Visibility" and you are able to hide Scene Items (audio as well)

**Comment by XC3N** [comment]
oh wow! yes indeed I had a look at that menu and completely skiped it as I didn't think it would do what I want to do... I would suggest a press+hold popup menu that says "hide" + maybe a pop up on first time explaining to go to the ... menu to manage it.

Thanks for everything!

**Comment by Kounex** [comment]
Yeah I will try out something else - always tough finding that sweet spot around of how to embed such features. Too much popups and stuff can get annoying fast as well. But I will definitely play around and bit! :)
