### ISSUE TITLE
Request - Access OBS outside the local network

### ISSUE THREAD

**Issue by reedog117** [Kounex/obs_blade#5]
Any reason why I can’t put in an arbitrary IP and port to connect to any OBS anywhere versus just on my local network? This will be good for people running OBS in datacenters using services like NoRIP.io, IRL Toolkit, or others.

**Comment by Kounex** [comment]
Didn't know such services exist! So it's basically a remote OBS instance where we can stream our desktop / client to and the remote OBS instance will finally stream it? Sounds interesting!

Initially "only" allowed IP addresses since the common use case is to connect to your local OBS instance and this will make it more obvious and the underlying WebSocket function works the easiest with IP addresses. I will think about a way on how to enable putting in "whatever" you want but still recommending to use (local) IP addresses to avoid misunderstandings :)

**Comment by REDDDDY** [comment]
> Didn't know such services exist! So it's basically a remote OBS instance where we can stream our desktop / client to and the remote OBS instance will finally stream it? Sounds interesting!
> 
> Initially "only" allowed IP addresses since the common use case is to connect to your local OBS instance and this will make it more obvious and the underlying WebSocket function works the easiest with IP addresses. I will think about a way on how to enable putting in "whatever" you want but still recommending to use (local) IP addresses to avoid misunderstandings :)

We would be really grateful if you could help and update it to allow hostname address as an alternative options to the standard
IP address.

**Comment by Kounex** [comment]
I checked the WebSocket API I'm using in the app and it allows for URI (so hostnames are possible). I don't have a testing environment for using hostnames though, so I can only implement the possibility and hope it actually works for the use cases people have when connecting in this way.

Just a short question: I assume you currently have other tools which enable connecitng via hostnames? If so: maybe you could tell me which and if you write the hostname with a specific protocol or without? For example:

`https://example.com` or `wss://example.com` or just `example.com`

**Comment by djr0x** [comment]
> I checked the WebSocket API I'm using in the app and it allows for URI (so hostnames are possible). I don't have a testing environment for using hostnames though, so I can only implement the possibility and hope it actually works for the use cases people have when connecting in this way.
> 
> Just a short question: I assume you currently have other tools which enable connecitng via hostnames? If so: maybe you could tell me which and if you write the hostname with a specific protocol or without? For example:
> 
> `https://example.com` or `wss://example.com` or just `example.com`

Thanks, when is the release of the app for ios which enables hostname ddns? thank you

**Comment by Kounex** [comment]
Slowly able to dedicate some time to work on this app again and this feature is almost done :)

<img width="561" alt="image" src="https://user-images.githubusercontent.com/13067046/167306527-3365823b-abef-45d2-9c3d-7faa7039c08d.png">

@t03i Thanks for providing some additional information! Currently I'm planning on providing no protocol scheme when trying to connect via domain mode just so it's possible to leave them out if the (managed) OBS instance does not need it (so just using `example.com`) but still being able to use one if necessary (`http`, `https`, `wss` etc.)

Will bundle this feature with some other I'm working on currently and plan to bundle it all in a `2.1.0` release coming soon! (no ETA though)

**Comment by t03i** [comment]
Great to hear!
That looks like a cool solution! 

Another angle: as I understood it, OBS blade is currently locked to IPv4. 
That means you can match the input using a regexp, e.g.: `^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$` [[1]](https://riptutorial.com/regex/example/14146/match-an-ip-address). If it does not match, you could assume it is a hostname and try calling the API with a hostname. 

Thanks for working on it, I am looking forward to `2.1.0`.

**Comment by Kounex** [comment]
True that would be possible as well - the input is already tested for validation so this kind of automation is already possible to implement. While I was planning the implementation, I came to the (personal) conclusion that it might be more obvious / easier to understand and use if I let the user actively decide in which form they want to connect! If I hide it behind some form of automation, users might question their input and don't know what kind of input is "allowed" / possible in general.

For now I would leave it as seen in the screenshot and see how it works out! I'm open to adjust of course :)

**Comment by Kounex** [comment]
v3.0.0 is rolling out which allows to enter domains - enjoy! 🎉

**Comment by REDDDDY** [comment]
Hey guys,
Thank you for sharing the good news and looping me in.
Just wanted to touch base with everyone on when can we expect to have new
updates on Google Playstore for Android versions of v3.0.0

Have another great day ahead! 🙂

**Comment by Kounex** [comment]
I pushed iOS and Android simultaneously into the stores, but on Google Play it's currently stuck on "In Review" since Sunday

![image](https://user-images.githubusercontent.com/13067046/187364204-39cbe05d-f5d2-42cb-8704-1588021f79a8.jpeg)

Nothing we can do in the meantime than wait! :/

**Comment by Kounex** [comment]
<img width="513" alt="image" src="https://user-images.githubusercontent.com/13067046/187397545-2a280301-5215-4485-a62b-a2d53f77e169.png">

Should be downloadable soon - enjoy! :)
