### ISSUE TITLE
Ability to reset chatbox widgets back to default

### ISSUE THREAD

**Issue by thegamingstig** [Kounex/obs_blade#50]
After I tried click on setting/manage moderation settings in the chat widget, it navigates me to the twitch setting webpage. But I cannot exit out of the page and go back to the normal chat display.

**Comment by Kounex** [comment]
It should be possible to reset by changing the user, right? I can see if a "refresh" button can be squeezed in though

**Comment by Kounex** [comment]
The tradeoff of not having to change the current chat to trigger a refresh vs. a dedicated refresh button which will hardly be used and just clutters the UI is not worth it. Closing for now. If more users have this issue and have good arguments to add something like that, we can talk again! 😄
