### ISSUE TITLE
Access Items within a Source Group

### ISSUE THREAD

**Issue by BenMannMann** [Kounex/obs_blade#58]
Heya,

Not sure if this is already a feature (I must be blind if it already is...) but is it possible to access items that are within a source group? Currently OBS Blade shows the Source Group but does not have any actions to open the group and see what's in it.

For example, I have a test text source within a group in OBS:
![example](https://github.com/Kounex/obs_blade/assets/14131644/9653f416-4da7-49f9-aaa8-70ffe8b76497)

OBS Blade only shows the group, nothing within it:
![example 2](https://github.com/Kounex/obs_blade/assets/14131644/95c35d3c-4b08-4e5c-83a5-bbbfcc94faa8)

Cheers!

**Comment by Kounex** [comment]
It should open up by tapping the folder icon - can you check that?

**Comment by BenMannMann** [comment]
> It should open up by tapping the folder icon - can you check that?

I am a silly goose, yes it does!

Thank you very much (and apologies for wasting your time!).

**Comment by Kounex** [comment]
No worries! It shows that it's currently not obvious - I will see if I find a better way to show that it's tapable 😊
