### ISSUE TITLE
In App Purchase error

### ISSUE THREAD

**Issue by mastermetal08** [Kounex/obs_blade#6]
iPadOs 15
Wanted to try Blacksmith but IAP is not working. Always giving error that there is no internet connected.

![2E59D01B-B1DE-43BF-82AF-8DE88099E9C6](https://user-images.githubusercontent.com/58204013/144699646-56a706d0-ef4b-4399-8dc5-787225b5ea14.png)
![E3FACBA9-75BA-4876-9635-9EA7D0F732C5](https://user-images.githubusercontent.com/58204013/144699647-d74009ec-073b-4b9f-8d92-9c42f2868014.png)

**Comment by Kounex** [comment]
Thanks for letting me know! I am looking into this and updating you once I found a solution and uploaded a new version! :)

**Comment by Kounex** [comment]
I uploaded version 2.0.1 which should fix this problem! It’s currently in „Waiting for review“ at Apple - should available in the next days! :)

**Comment by d4MikeJones** [comment]
I have an issue that may be related to this as well. I keep IAPs disabled in general and every time I launch the app, I get an alert popup that "In-app purchases are not allowed". I don't see anything from the app itself prompting me about purchases, and if I launch the app while IAPs are enabled then I don't see anything at al
![PNG image](https://user-images.githubusercontent.com/91276506/144762385-e23a4abe-9ce1-4123-9b5d-2dec3df5ebf1.png)
l.

**Comment by Kounex** [comment]
Oh damn! Thanks for letting me know! As I wrote in my previous comment, a new version is on its way to the App Store. Would be great if you can check if this still happens once you were able to update!

**Comment by Kounex** [comment]
Since I haven’t received any feedback that it’s still not working after the update, I assume it works now! Feel free to re-open the issue if there re still problems regarding in app purchases! :)
