### ISSUE TITLE
No recording timer?

### ISSUE THREAD

**Issue by kibbblz** [Kounex/obs_blade#7]
I really love this app and I used it a lot for streaming but recently for recording and I noticed there’s no recording time shown anywhere? For streaming I would use the stats box at the bottom. Can we maybe get a recording timer somewhere with the dropped frames and all that? I think even the timer should be up top near the recording button or something to prevent scrolling down just to see that. But at the same time have a stats box at the bottom to check if there’s any problems like I would when I was streaming.  Thanks!

**Comment by Kounex** [comment]
As I was implementing this for the Streaming part (timer and stats), I wanted to do the same for the recording purpose but unfortunately it was not possible/available. I’m bound to what the WebSocket plugin enables and there are no stats or recording timer (at least when I was implementing it)

i will take a look if there has been any updates to the plugin which makes this possible and let you know :)

**Comment by kibbblz** [comment]
I would absolutely love this. I have to use my iPad for a timer and split the screen to see both apps. I am not sure what you mean by no stats or recording timer but on OBS itself there is a timer when you record videos. ![image](https://user-images.githubusercontent.com/17756408/149634028-a84bf1a8-bec0-4e88-a884-8be7ba698bbe.png)

**Comment by Kounex** [comment]
OBS itself does this, yes! But in order for OBS Blade to get information from OBS, I rely on the WebSocket plugin (what you need to install before using it, what I mentioned in the introduction) and a while back the plugin did not expose this information!

But I will let you know once I was able to look into this! :)

**Comment by kibbblz** [comment]
So another thing I also noticed you might be able to fix is when you record, the Pause button stays orange and when you pause the button is still orange saying Resume. It sometimes confuses me and I have to keep double checking. I know it says Recording above the button with a green dot but it's kinda small so I think it would be better if the big orange button is green as well when recording, so it would say Pause (green button) and Resume (orange) since paused shows an orange dot too. It is just easier for me to quickly glance at the app and look at the color where it says Pause/Resume and I can then associate colors with what's going on. I really appreciate your work on this app, it's a life saver for me because I use it daily for recordings.

**Comment by Kounex** [comment]
Ah I will take a look at this as well, currently occupied so it will take some time, but I will update this issue once I was able to take another look at the API for the recording timer and the color of the buttons in general! :)

**Comment by kibbblz** [comment]
Dunno why I never mentioned this but another neat feature would be to also show the size left on disk like it does on OBS. Timer and disk space available are things I always need to see but have to keep alt tabbing to OBS to check that. Just another idea that’s all.

**Comment by kibbblz** [comment]
Just checking in. I still really want to see a record/stream timer via the app if possible. Any updates?

**Comment by Kounex** [comment]
👀
<img width="564" alt="image" src="https://user-images.githubusercontent.com/13067046/168665752-e741b7e5-a0d2-48c6-ba95-68a786d23da4.png">
No ETA as I'm bundling some features, but... _shouldn't take too long_™

**Comment by Kounex** [comment]
v3.0.0 is rolling out which finally has a recording timer - enjoy! 🎉

**Comment by kibbblz** [comment]
Awesome, thank you very much for this!
