### ISSUE TITLE
Crash on iPad Pro

### ISSUE THREAD

**Issue by c0rychu** [Kounex/obs_blade#8]
It cannot be opened on iPad Pro 11" (M1 chip), iOS 15.3.
It just keeps crashing.

**Comment by Kounex** [comment]
When did this happen? After a fresh install or after an update? Did it work once on this device or did it crash from the beginning?

**Comment by c0rychu** [comment]
Sorry. It was problematic in iOS 15.2. After updating to 15.3, delete the app and reinstall it, it works fine:)

**Comment by Kounex** [comment]
Still weird that it crashed in the first place! Glad that it worked out though :)

Closing this for now - if you encounter this problem again, feel free to open this issue again!
