### ISSUE TITLE
Where to find Youtube Channel ID?

### ISSUE THREAD

**Issue by SupaGlick** [Kounex/obs_blade#9]
I went into my youtube settings, into advanced settings and got my Channel ID from there but it does not work and doesnt pull up my youtube chat. The only way it works is if I use the string at the end of the youtube.com/watch?v=_______, but that changes with every livestream. Does that mean I have to update the ID every time I stream?

**Comment by Kounex** [comment]
Currently, yes :/ Since YouTube does not expose this "Chat feature" as freely as Twitch does, I need to rely on the ever changing URL (thats why I marked it as beta).

I will take a look if another method of accessing the YouTube Chat has been made available in the meantime and let you know! :)
